### ISSUE TITLE
New Package - medical-docs

### ISSUE THREAD

**Issue by wressl** [federico-terzi/espanso-hub#15]
This package is to assist with medical documentation. 
The link is: https://github.com/wressl/medical-docs

I would like to make this initial version available, but I intend to keep improving it.
How do package versions work?  
Should I continue to develop in 0.1.0 and installs will always pull the latest check-in?
Or should I create a new directory (like 0.1.1) and work in there, so installs would always grab the 0.1.0 version until I ask you to update the current version to 0.1.1?

**Comment by federico-terzi** [comment]
Hey @wressl,

> This package is to assist with medical documentation.
> The link is: https://github.com/wressl/medical-docs

Great, I'll add it to the hub as soon as I can :)

> I would like to make this initial version available, but I intend to keep improving it.
> Or should I create a new directory (like 0.1.1) and work in there, so installs would always grab the 0.1.0 version until I ask you to update the current version to 0.1.1?

This is the correct approach. I'll publish your package (v0.1.0) on the hub, and that is basically a "snapshot" of your package up to that point. Then, when you will be ready for the new version, you can create a new issue (or comment on this one), so that I'll add the new version (0.1.1) on the hub.

Cheers :)

**Comment by federico-terzi** [comment]
I've added your package to the hub: [https://hub.espanso.org/packages/medical-docs/](https://hub.espanso.org/packages/medical-docs/)

I checked it out and it's really impressive! Good job
